baseURL = 'https://adamperkowski.dev/'
languageCode = 'en-us'
theme = 'terminal'
title = "Adam Perkowski"
subtitle = "Just a random developer"
keywords = ['adam', 'perkowski', 'github', 'rust', 'programming', 'developement', 'programmer', 'developer', 'highlightos']
enableRobotsTXT = "true"

[sitemap]
changefreq = "weekly"
priority = 0.5

[pagination]
pager_size = 5

[markup.goldmark.renderer]
unsafe = true


[params]
contentTypeName = "posts"
showMenuItems = 3
showLanguageSelector = true
autoCover = true
showLastUpdated = false
centerTheme = true
wakatime = "This is a string from the config file."

[params.logo]
logoText = "hello world"


[languages]

[languages.en]
languageName = "English"

[languages.en.params]
menuMore = "More"
readMore = "Read more"
readOtherPosts = "Other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
missingContentMessage = "Page not found :o"
missingBackButtonLabel = "Homepage"

[languages.en.params.logo]
logoHomeLink = "/"

[languages.en.menu]

[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = 1

[[languages.en.menu.main]]
identifier = "posts"
name = "Blog"
url = "/posts"
weight = 2

[[languages.en.menu.main]]
identifier = "donate"
name = "Donate"
url = "/donate"
weight = 3

[[languages.en.menu.main]]
identifier = "privacy"
name = "Privacy policy"
url = "/privacy"
weight = 4


[languages.pl]
languageName = "Polski"

[languages.pl.params]
menuMore = "Więcej"
readMore = "Czytaj dalej"
readOtherPosts = "Inne posty"
newerPosts = "Nowsze posty"
olderPosts = "Starsze posty"
missingContentMessage = "Strona nie znaleziona :o"
missingBackButtonLabel = "Strona główna"

[languages.pl.params.logo]
logoHomeLink = "/pl"

[languages.pl.menu]

[[languages.pl.menu.main]]
identifier = "about"
name = "O mnie"
url = "/pl/about"
weight = 1

[[languages.pl.menu.main]]
identifier = "posts"
name = "Blog"
url = "/pl/posts"
weight = 2

[[languages.pl.menu.main]]
identifier = "donate"
name = "Przekaż darowiznę"
url = "/donate"
weight = 3

[[languages.pl.menu.main]]
identifier = "privacy"
name = "Polityka prywatności"
url = "/pl/privacy"
weight = 4
